### ISSUE TITLE
check-commit-style toggles automerge-skip label

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/actions#122]
I've noticed that the `check-commit-style` action doesn't add the `automerge-skip` label appropriately. Instead, it seems to toggle whether the label is applied or not. For example, opening a PR with an invalid commit will cause `automerge-skip` to be added. If you then force push a new commit that is still invalid, the `automerge-skip` label is removed. It should not be because the commit is still invalid.

I've noticed this a few times in homebrew/core, but I've opened a PR on a custom tap that illustrates the problem blocking any homebrew/core changes: https://github.com/Rylan12/homebrew-development/pull/5

I created the PR based on https://github.com/Rylan12/homebrew-development/commit/e4b004c040c6b2d71f4c0f30ea75462c3b0346ed and the `automerge-skip` label [was applied](https://github.com/Rylan12/homebrew-development/pull/5#event-4043895364).

Then, I forced pushed the branch to https://github.com/Rylan12/homebrew-development/commit/e640a2d4b0397493f82dd5a1e65a9e8c0e31cbdd and the `automerge-skip` label [was removed](https://github.com/Rylan12/homebrew-development/pull/5#event-4043900728).

Both commits modify two files so the label should still be present.

I haven't done any testing yet to determine where the bug is. If I have time later, I'll try to take a look but I figured I'd file this in case someone else has an idea.

**Comment by Rylan12** [comment]
Good news, I don't think this is an issue with the `check-commit-style` action!

Instead, it's a bug in the `label-pull-requests` configuration that we use in homebrew/core. In our configuration, we set:

```json
{
  "label": "automerge-skip",
  "path": "Formula/(patchelf|binutils).rb"
}
```

This means that BrewTestBot will add `automerge-skip` for PRs that modify `Formula/patchelf.rb` and `Formula/binutils.rb`. However, because a rule was defined for the `automerge-skip` label, the action now thinks that the label should be removed when the PR _doesn't_ modify either of those file. The easiest way to fix this is probably to use a different label in that configuration (either `do not merge` or a new label that will not automerge PRs).

**Comment by reitermarkus** [comment]
Fixes by https://github.com/Homebrew/actions/pull/125.https://github.com/Homebrew/actions/pull/125

**Comment by reitermarkus** [comment]
Actually, no, will be fixed by https://github.com/Homebrew/actions/pull/126.
