### ISSUE TITLE
Triage action runs twice in brew

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/actions#132]
see https://github.com/Homebrew/brew/pull/10039#issuecomment-746706125, https://github.com/Homebrew/brew/pull/10039#issuecomment-746706128

**Comment by jonchang** [comment]
Did you label the issue while creating the pull request, or immediately afterwards? If it's the latter it's likely just a race condition, since the triage workflow runs on both label events and pull request open events.

**Comment by dtrodrigues** [comment]
I'm 95% sure I labeled it while creating via the GUI, but it's possible I did it afterwards. I'll try again to replicate.

**Comment by dtrodrigues** [comment]
Hmm, it didn't seem to happen just now with https://github.com/Homebrew/brew/pull/10042. I'll close this.
