### ISSUE TITLE
Allow external taps to use setup-homebrew on self-hosted runners

### ISSUE THREAD

**Issue by shivammathur** [Homebrew/actions#138]
It would be nice if external taps can also use `setup-homebrew` action with self-hosted runners.
Please remove this check.

https://github.com/Homebrew/actions/blob/9ef2855601309e0f67b16550143864ae330da029/setup-homebrew/main.sh#L102-L105

**Comment by MikeMcQuaid** [comment]
You already can use it, just don't set `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED`.

**Comment by shivammathur** [comment]
@MikeMcQuaid 
If you repo is homebrew-tap, then it creates a symlink `_work/homebrew-tap/homebrew-tap` and on next run the `set up job` step fails as it wants to create `_work/homebrew-tap/homebrew-tap` directory but that is a symlink.

**Comment by MikeMcQuaid** [comment]
@shivammathur We'll review a PR to improve this behaviour.
