### ISSUE TITLE
Bump Cask PR

### ISSUE THREAD

**Issue by smark91** [Homebrew/actions#245]
Does it make sense to have an action for updating cask too?
Is it present for forumulae but not cask.

**Comment by SMillerDev** [comment]
It does, it just seems like nobody did yet.

**Comment by xakep8** [comment]
I guess we can do ```brew upgrade --cask``` which does the job. Am I right about this?

**Comment by SMillerDev** [comment]
That's not a CI action though.

**Comment by xakep8** [comment]
I am trying to write a action.yml for the given task but I was also searching for alternatives to do the same.

**Comment by cho-m** [comment]
@SMillerDev I think you completed this in https://github.com/Homebrew/actions/pull/354 ? Is it safe to close issue?

**Comment by SMillerDev** [comment]
Yeah, seems like it
