### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by OliverLSanz** [Homebrew/actions#316]
This warning is shown when using the [setup-homebrew](https://github.com/Homebrew/actions/tree/master/setup-homebrew) action.

>Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by carlocab** [comment]
In progress at #315.

**Comment by Bo98** [comment]
This is fixed for setup-homebrew.

`review-cask-pr` and `remove-disabled-formulae` are still being worked on but they are largely for internal use.
