### ISSUE TITLE
what changed? wont install newest version anymore

### ISSUE THREAD

**Issue by Geczy** [Homebrew/actions#395]
trying to install this cask https://github.com/Homebrew/homebrew-cask/blob/master/Casks/krisp.rb

but it keeps defaulting to this version https://github.com/Homebrew/homebrew-cask/blob/442efaf693567a00551a59b4b39de33002106433/Casks/krisp.rb

even your main site is showing old https://formulae.brew.sh/cask/krisp

**Comment by MikeMcQuaid** [comment]
Actually, no, this changed two days ago and should really be updated by now.
