### ISSUE TITLE
setup-homebrew doesn't work in self-hosted GHA runners

### ISSUE THREAD

**Issue by bixu** [Homebrew/actions#436]
We use a lot of self-hosted runners, and would love to use your `setup-homebrew` action on them, but we see errors like:

```
/usr/bin/bash /runner/_work/_actions/Homebrew/actions/master/setup-homebrew/main.sh false false auto false 
Could not find 'brew' command in PATH or standard locations.
Error: The process '/usr/bin/bash' failed with exit code 1
```

After invoking like:

```
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
```

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/actions/blob/30dee6e7aa635449d7cd216017e9b9ab110dba42/setup-homebrew/main.sh#L42-L50

Homebrew needs to be already installed in the default location for that platform and then it will keep it up-to-date.
