### ISSUE TITLE
GitHub authorization header construction can fail on Linux

### ISSUE THREAD

**Issue by jpeach** [Homebrew/actions#457]
If the setup-homebrew action is configured with a custom GitHub token, then when the action encodes it into a basic authorization header using [base64](https://man7.org/linux/man-pages/man1/base64.1.html), it can end up being split into multiple lines because the default Linux behavior is to wrap the output at 76 columns. This results in a broken Authorization header, and GitHub access failing with HTTP 400 responses.

**Comment by jpeach** [comment]
I confirmed that the "setup-homebrew" action now works with my private tap. Thanks @Bo98 and @MikeMcQuaid!

**Comment by MikeMcQuaid** [comment]
You're welcome @jpeach
