### ISSUE TITLE
Node.js 16 actions are deprecated waring for Homebrew/actions/setup-homebrew

### ISSUE THREAD

**Issue by air3ijai** [Homebrew/actions#484]
We are getting a warning at the end of the workflow run with the following message

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Homebrew/actions/setup-homebrew@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Bo98** [comment]
We're aware and will have it sorted by the end of the month hopefully, and certainly well before it becomes an issue.

**Comment by SethTisue** [comment]
No, don't auto-close!

**Comment by SethTisue** [comment]
in under the wire ;-)
