### ISSUE TITLE
setup-homebrew action is failing

### ISSUE THREAD

**Issue by JulianSchmidgall** [Homebrew/actions#537]
I try to install Homebrew with the action `setup-homebrew`:

```
- name: Set up Homebrew
  id: set-up-homebrew
  uses: Homebrew/actions/setup-homebrew@master
```

Unfortunately the action is failing with:

> Could not find 'brew' command in PATH or standard locations.
Error: The process '/bin/bash' failed with exit code 1

The workflow runs on a self-hosted Linux runner with the version `2.311.0`

I would be happy about any hints.

**Comment by SMillerDev** [comment]
`Homebrew/actions/setup-homebrew@master` sets up an existing Homebrew install to be used in CI. So you need to install Homebrew before doing this.
