### ISSUE TITLE
Support using `secrets.GITHUB_TOKEN` for sending PRs 

### ISSUE THREAD

**Issue by Goooler** [Homebrew/actions#584]
I replaced the custom GitHub access token with `${{ secrets.GITHUB_TOKEN }}` when using `Homebrew/actions/bump-packages`, which should be able to send PRs on GHA, but with an error:

```
Error: Failure while executing; `/usr/bin/env git push --set-upstream https://******@github.com/Goooler/homebrew-repo bump-kotlin-explorer-1.6.0:bump-kotlin-explorer-1.6.0` exited with 128. Here's the output:
fatal: could not read Password for 'https://***@github.com': Device not configured

Error: Failure while executing; `/usr/bin/env git push --set-upstream https://******@github.com/Goooler/homebrew-repo bump-kotlin-explorer-1.6.0:bump-kotlin-explorer-1.6.0` exited with 128. Here's the output:
fatal: could not read Password for 'https://***@github.com': Device not configured
```

It failed to create PR here, I believe we can replace this step with `gh pr create ...` for creating  PRs on GitHub Actions, which uses GitHub official's GH CLI to do the same thing, without explicit PAT declared. 

- workflow run: https://github.com/Goooler/homebrew-repo/actions/runs/10693966513/job/29644969347
- workflow file: https://github.com/Goooler/homebrew-repo/blob/ce88cff549605c6231d3eba3c54d8b2a31727d3e/.github/workflows/autobump.yml#L20-L32

**Comment by Goooler** [comment]
According to [Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), it's able to send PRs on CI, the issue might be related to the wrong usage of it, fixing the usage will also resolve this issue.

**Comment by Goooler** [comment]
```
Error: Failure while executing; `/usr/bin/env git push --set-upstream ***github.com/Goooler/homebrew-repo bump-kotlin-explorer-1.6.0:bump-kotlin-explorer-1.6.0` exited with 1. Here's the output:
To https://github.com/Goooler/homebrew-repo
 ! [rejected]        bump-kotlin-explorer-1.6.0 -> bump-kotlin-explorer-1.6.0 (non-fast-forward)
error: failed to push some refs to 'https://github.com/Goooler/homebrew-repo'
```

https://github.com/Goooler/homebrew-repo/actions/runs/10700380504/job/29663997922

**Comment by carlocab** [comment]
Delete your `bump-kotlin-explorer-1.6.0` branch and try again.

**Comment by Goooler** [comment]
```
Error: Unable to open pull request: GitHub API Error: Resource not accessible by integration
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens
```

https://github.com/Goooler/homebrew-repo/actions/runs/10700629318/job/29664778250

**Comment by carlocab** [comment]
Your `GITHUB_TOKEN` needs write access to pull requests.

Please use the [discussions page](https://github.com/orgs/Homebrew/discussions) if you need more help.
