### ISSUE TITLE
cancel-previous-runs sometimes attempts to cancel a completed run

### ISSUE THREAD

**Issue by ddelange** [Homebrew/actions#70]
Hi :)

On cancel-previous-runs (mostly running fine), I just encountered a [`HttpError: Cannot cancel a workflow run that is completed.`](https://github.com/ddelange/homebrew-ffmpeg/pull/1/checks?check_run_id=1050244846#step:2:3).

Workflow yaml: https://github.com/ddelange/homebrew-ffmpeg/blob/f3a0e84b4e1c663e684d10fcc790fe3748e1e35d/.github/workflows/main.yml

Not sure what the right way of catching/avoiding this would be.

**Comment by dawidd6** [comment]
This Action is meant to be run on schedule.
