### ISSUE TITLE
cancel-previous-runs make workflow an optional argument

### ISSUE THREAD

**Issue by ddelange** [Homebrew/actions#71]
Most likely the cancel-previous-runs was written to support cron jobs, but I actually like having it inside the action itself.

To avoid hardcoding a `workflow_id`, I [tried](https://github.com/ddelange/homebrew-ffmpeg/blob/bf0341431d9aedf36f2dea941f02291775e82e59/.github/workflows/main.yml#L22) for a while to programmatically get the `workflow_id` to pass to this action. I gave up in the end and hardcoded `'main.yml'`.

I saw this other repo has a [workaround](https://github.com/n1hility/cancel-previous-runs/blob/2e3c1893986568a2197c41957b9c809cbcf1a61e/src/main.ts#L48-L66), such that it is not a required argument anymore (only required when using as cron job).

How about having a similar workaround in this action?

**Comment by ddelange** [comment]
closing as useless on schedule, ref https://github.com/Homebrew/actions/issues/70

**Comment by dawidd6** [comment]
I think we would like to port this Action anyway to run it on pull_request event. So if you want you can try your luck in porting it. If not, then maybe I'll do it, but not anytime soon.

**Comment by ddelange** [comment]
Currently I skipped to the quick solution :) https://github.com/ddelange/homebrew-ffmpeg/blob/34b176477618fa9c8bc5954f3c08ed1dd348250a/.github/workflows/main.yml#L9
